apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-cicd-app
  labels:
    app: python-cicd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-cicd-app
  template:
    metadata:
      labels:
        app: python-cicd-app
    spec:
      containers:
      - name: python-cicd-app
        image: vinay74/myfirst-cicd:6
        ports:
        - containerPort: 6000
